replicaCount: 1

image:
  repository: ghcr.io/cq-pandora/assets
  pullPolicy: Always
  tag: bot

webimage:
  repository: ghcr.io/cq-pandora/assets
  pullPolicy: Always
  tag: web

pandora-configs:
  custom_translation_indices.json: {}
  emojis.json: {
    "weapon_ticket": "<:weapon_ticket:490997284847353856>",
    "sbw_ticket": "<:sbw_ticket:490996375014735877>",
    "premium_contract": "<:premium_contract:490995984504193024>",
    "option_ticket": "<:option_ticket:490997214320263188>",
    "key": "<:key:490994307055091723>",
    "iron": "<:iron:490994481496064013>",
    "honor": "<:honor:490996726941876244>",
    "hero_select": "<:hero_select:490996230164447245>",
    "gold": "<:gold:490994829514244097>",
    "gem": "<:gem:490995206246629386>",
    "fishcoin": "<:fishcoin:491012192628506635>",
    "fergus_ticket": "<:fergus_ticket:490994631819919361>",
    "crystal_dust": "<:crystal_dust:490994889446653982>",
    "crystal_chard": "<:crystal_chard:490994929284284417>",
    "crystal": "<:crystal:490995085849133067>",
    "costume_ticket": "<:costume_ticket:490996498163564567>",
    "contract_only_contract": "<:contract_only_contract:490997070698643456>",
    "colo_ticket": "<:colo_ticket:490995494516948994>",
    "mossy_cat_chest": "<:mossy_cat_chest:491026925096271913>",
    "intact_cat_chest": "<:intact_cat_chest:491026925184352277>",
    "mini_promotable": "<:mini_promotable:492567725722566667>",
    "mini_contract": "<:mini_contract:492568041649864705>",
    "mini_brown": "<:mini_brown:492570507993153537>",
    "mini_supply": "<:mini_supply:498853343649726465>",
    "mini_event": "<:mini_event:498853343863635968>"
  }
  links.json: [
    {
      "title": "Guides",
      "entries": [
        {
          "title": "Guide to Almost Everything",
          "url": "http://bit.ly/CQEverythingGuide"
        },
        {
          "title": "Hero skills/builds list",
          "url": "http://bit.ly/2NNDlbg"
        },
        {
          "title": "AFK",
          "url": "http://bit.ly/CQAfkGuide"
        }
      ]
    },
    {
      "title": "Tier Lists",
      "entries": [
        {
          "title": "Definitely Original tier list",
          "url": "https://bit.ly/CQDefinitOrigTierlist"
        }
      ]
    },
    {
      "title": "Raid",
      "entries": [
        {
          "title": "kamakiller's Loki",
          "url": "https://bit.ly/CQLokiIncarnateReupload"
        },
        {
          "title": "Manacar Comic",
          "url": "https://goo.gl/aJ8Yoy"
        }
      ]
    },
    {
      "title": "Champions",
      "entries": [
        {
          "title": "Vyrlokar",
          "url": "https://s.fenrir.moe/vyrlokarhampionsuide"
        }
      ]
    },
    {
      "title": "How To Get",
      "entries": [
        {
          "title": "Monuments",
          "url": "http://bit.ly/CQMonumentsReupload"
        },
        {
          "title": "Lionel's skin",
          "url": "https://goo.gl/9BXBkD"
        },
        {
          "title": "Himiko's skin",
          "url": "https://goo.gl/5yDbjr"
        }
      ]
    },
    {
      "title": "Challenge",
      "entries": [
        {
          "title": "kamakiller",
          "url": "https://bit.ly/CQChallengeModeReupload"
        },
        {
          "title": "Sigils list",
          "url": "http://bit.ly/2NCLFu9"
        }
      ]
    },
    {
      "title": "LoPF",
      "entries": [
        {
          "title": "Nyaa",
          "url": "https://goo.gl/iqppI0"
        },
        {
          "title": "Shintouyu",
          "url": "https://goo.gl/4i8nCb"
        },
        {
          "title": "LoPF map",
          "url": "https://goo.gl/YtlDQH"
        }
      ]
    },
    {
      "title": "Hasla Guides",
      "entries": [
        {
          "title": "Comics",
          "url": "https://goo.gl/HPsANc"
        },
        {
          "title": "Season 2",
          "url": "https://goo.gl/UQdjhw"
        },
        {
          "title": "Berry system",
          "url": "https://goo.gl/jbgmLa"
        }
      ]
    },
    {
      "title": "Miscellaneous",
      "entries": [
        {
          "title": "Google Drive Folder",
          "url": "http://bit.ly/CQResources"
        },
        {
          "title": "Leveling guide",
          "url": "https://i.redd.it/ya5mgw9xvfk01.jpg"
        },
        {
          "title": "cq-assets",
          "url": "https://github.com/cq-pandora/assets/"
        },
        {
          "title": "block-map",
          "url": "http://bit.ly/CQBlockMap"
        }
      ]
    }
  ]


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env: []
envSecrets: 
- pandora-envs

serviceAccount:
  create: true
  annotations: {}
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# service:
#   type: ClusterIP
#   port: 80

service:
  type: LoadBalancer
  port: 80

# ingress:
  # enabled: false
  # className: ""
  # annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # hosts:
  #   - host: pandora.local
  #     paths:
  #       - path: /
  #         pathType: ImplementationSpecific
  # tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

ingress:
  enabled: true
  className: nginx
  # annotations: {}
  hosts:
  - host: data.fenrir.moe
    paths:
    - path: /
      pathType: Prefix

resources:
  limits:
    memory: 768Mi
  requests:
    cpu: 100m
    memory: 128Mi

webResources:
  limits:
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 32Mi

nodeSelector: {}

tolerations: []

affinity: {}
