apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    name: argocd
spec:
  project: infra

  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.1.3

    helm:
      values: |
        configs:
          secret:
            createSecret: false
          cm:
            url: "https://argocd.tenma.moe"
            dex.config: |
              connectors:
              - name: authentik
                type: oidc
                id: authentik
                config:
                  issuer: https://auth.tenma.moe/application/o/argocd/
                  clientID: 891ea8b5bc1e6f22829db5b9f2bf73f8423e3526
                  clientSecret: $dex.authentik.clientSecret
                  insecureEnableGroups: true
                  scopes:
                  - openid
                  - profile
                  - email
                  - groups
          rbac:
            policy.csv: |
              g, ArgoCD Admins, role:admin
        server:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
              external-dns.alpha.kubernetes.io/ttl: "120"
            hosts:
            - argocd.tenma.moe

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5
