apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubed
  namespace: argocd
  labels:
    name: kubed
spec:
  project: infra

  source:
    repoURL: https://charts.appscode.com/stable/
    chart: kubed
    targetRevision: 0.12.0

    helm:
      values: |

  destination:
    server: https://kubernetes.default.svc
    namespace: kubed

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5