apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: postgresql
spec:
  interfaceName: eth0
  node: depsos
  expectedIPs: []
  # - 192.168.20.37
  profiles: []
  ports:
  - name: postgres
    port: 5432
    protocol: UDP
