apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: screeps
  namespace: argocd
  labels:
    name: screeps
spec:
  project: games

  source:
    repoURL: https://truelecter.github.io/charts/
    chart: screeps
    targetRevision: 1.0.5

    helm:
      values: |
        env:
          MONGO_HOST: depsos
        config:
          version: latest
          mods:
          - screepsmod-mongo
          - screepsmod-auth
          bots:
            simplebot: "screepsbot-zeswarm"
          backup:
            dirs:
            - tests
            # - bots/overmind
          serverConfig:
            welcomeText:  |
              <style>.screepsplus h1{  text-align: center; }</style>
              <div class="screepsplus">
              <h1>ScreepsPlus</h1>
              Mods include screepsmod-auth and several custom mods to enable email notifications, control tickrate, power banks, portals, and other internal improvements.<br><br>
              <div style="text-align: center">
              This server is funded by backers on Patreon. <br>
              <a target="_blank" href="https://www.patreon.com/bePatron?u=6867142" ><img src="https://c5.patreon.com/external/logo/become_a_patron_button.png"></a>
              </div>
            constants:
              TEST_CONSTANT: 123
            tickRate: 2000

        service:
          type: ClusterIP
          externalPort: 443
          internalPort: 21025

        envSecrets:
        - screeps-envs

        ingress:
          enabled: true
          className: nginx
          hosts:
          - host: screeps.fenrir.moe
            paths:
            - path: /
              pathType: Prefix

        resources:
          limits:
            cpu: 2
          requests:
            cpu: 100m
            memory: 128Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: screeps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5