---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  description: Cluster wide addons
  sourceRepos:
  - '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: crusaders-quest
  namespace: argocd
spec:
  description: Crusaders Quest related stuff
  sourceRepos:
  - '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
