apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd
    namespace: argocd
spec:
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:+j9QLS/8nFqCu+Wx+w==,iv:3VwwqshW+dr9HPau9wLAfPcoCNWIdsN5gy+h2K4ITcI=,tag:oB3ZP8nEnhggdVFPFu4Grg==,type:str]
          stringData:
            server.secretkey: ENC[AES256_GCM,data:7EyRhVG057UNDwaSJ9tRAc1o9Xg=,iv:JRV3RJIlps6qIbPO0bLARKfI7DLJw28aUwHSKA+Paa4=,tag:i9QsS3DHPvWYMpL+ULauMg==,type:str]
            webhook.github.secret: ENC[AES256_GCM,data:6iWGO/c7l+CCzdfp/7Xvo7IiSzwPFfOVYRrCHQlsj13ZYlchoj6ae5wG7StwJmNbeHWRBsCBFXWIVmJ0np1JoKgzfSIbNWmnC42XO7OvtOge1Y/8sKICVmoMVRI23R7GDODfaQ==,iv:zzdEsJPgzybuZKt7ti1YbJbCHaLC0hWePEerhOfbiHo=,tag:Uy28yoB1sFPJEuoNuySbOw==,type:str]
            admin.password: ENC[AES256_GCM,data:2afv9qkRS6Hi5LGU9ppB04M2DC0LJo/cOZdXKCwNrbjs/gmHUE5q0psweoZbQyotIc7hYH4dZ/SYAeMf,iv:RX8TH6X/9OfqLboTOjBW9v7BcBOWzmD8XxqQB34WP9o=,tag:UTza5oIagctU6FGDUPD1LA==,type:str]
            admin.passwordMtime: ENC[AES256_GCM,data:AxgmE208VbWT9S8kgLmTtwVrIoKJOQ==,iv:nGGxFrGtzCp1puxTvMY57tcyXNqOmA4Z+K6zonI6j2s=,tag:2kwtm2WAnLHuc+d2xZQQYw==,type:str]
            dex.authentik.clientSecret: ENC[AES256_GCM,data:5jP2LmLQPB0496lotZ1LQJktvajov7xZmwnCiY1fPtO/x1Dd3k/6/1GiEBa+DzCrTm9LVZaiunQcQF5oqNuHy99kLwpA/CDgefE1CTMLy8y0Hzlfu41exycznXyZPWjKwvvuHq/lvQnWycVFJqPyQ6Y+m/aObouuwOJrDw4bxJs=,iv:OJquIDBpPgc3OShDI9NJ5n6TjgBm0ovQ9cMKLH2XIF4=,tag:KS1O/RIEfLbhEQmkAjOJQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-03T19:25:46Z"
    mac: ENC[AES256_GCM,data:RtId4dAVgcAG26aZ411NkijHNHdnXVjpd2YoCTAfpZf/rP6uSd+9OfIuVAjOwe6zIQ0fh/M91CONz7SqUBT2ogcivGS/gZ4s1I2IDMiLe4G1hkTijpQcQ8gZOLlDgwYGMyaLnK/d6QsTv99iECxFsdlFGqUIQn1beaXfpXY2nxA=,iv:B/5HMfFJ1gcFpnzDo2EaKEmaSm/8KK2VT8S7x6st1+Q=,tag:6cTKRffW/YKVQ1XfQp5Q4g==,type:str]
    pgp:
        - created_at: "2022-11-03T17:17:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzeYGILgZyj2AQ//YL+1he7fhZG/tqC5uLRmeLd27zxpoMu195fUeRTp/ymz
            gJE7J1hgmYZbUWRy3NKRDG/miS5e0mqiXwuGzTlHIAHuLDOAixyWji2YaC5UABQV
            bvtDyVL+cESnNl3PG4ybx3YN+OxOXsHlDNnIh5yNnzQGLlSWvqgCmgxtHSWZDvhN
            U0kazO0JtQ/uM4wUapmYYNS8d3FOiR7czZz4dFcEc1RSXgiLEqwKT7W6LCwSC+eo
            apf58jjO2eGie4jj278vx+MuyQ9KFjKcLR+aPaFzqMuExzWEodqLbkRRrc1wJ1kq
            IBCn88V5LuwhWztyisj2jnxZFbtJjuTT+rtLFKRtrUmg8zq0vTYcBgLeYi5BK/Oo
            tn0xEaO4VshAxwQvx+SAnp6LK5bFMK5Q4k/XcnaiFO5fkLjHsDW4k2Yj5NrTGTi2
            vmy2s5aufn5eXpqYcsNZXWBCKPI1GkVgORB3he4cLqboF3vx6tTsGXofQpzupX7w
            dto288iAmG2F+K7F8iughAthNas8zy6wpYaRrNoL26g6b/8pG8hFIUSNTDqqZxjj
            Kvsb7776KuIeoRbvVdy1MUMjO0QcomIZA6Lgm9JmAaOb3oDZMdC2ixxhCYtJ6JhH
            wGhQfh7l9tYEDjazWTPzXxM94RfBUw/q48A1eB0DQyYa+5XehzbbD9JszH6F0A/U
            ZgEJAhCx9lmxMO5F2eyLrWWhJlRgUjdtJAnNmgP9ZMU+Hia90hQuP5LBAYmJpqoF
            8Of83VSvyynMOujh5AEiaWSsbzx5kjQZaNlhh7h8q6dDXLCC3r54v6u3Zahx1mx+
            YSsjqvGSyQ==
            =U7gx
            -----END PGP MESSAGE-----
          fp: A35AABA719FAC1A001E375F8EEF7F5B1C5AB1F74
        - created_at: "2022-11-03T17:17:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA2EVWQAqdcBfAQv9HN0lFHE1ioxCNMXIIEgi1DkH/bVUtWl19qCjY/zahwCU
            YOydE2LsJjLsxllpUf5gudDx5vXzcwJEV+yPwyYPSA53cxPPd/9008jodOBOT7of
            RCiAuVmcIHpYb87PM8YVgk1KTrzubueQy3K8cyWPB3WG7nRGoXQiId3uBu8ZOyZA
            FyZ1sLS8UsT8GhFU3A7/ld0CbpfPkoLLzZqoqfgPKpBrHHyf38oRGHL4eXySgqFg
            1DhvlTPdbiDb8e1RtKc4VO+uqK31A3kLTuma2/tGxkdsHvjb9EJmrTzciIiCrpfY
            yZN3jqLv3vudxHvos+lY113oQuNQ8QeYtnXv4v3Y/BjjgKdmq70hCYCnSHAhTf0w
            JCgdolhBgfq735vIns+NMLVU4SFqAKUkQdPK67ipik993f00H+lXA7SVjpsZoZSr
            3si9QAt21qd0I4vDE9N/jIkFLq7ESoDxzMTbEXgWJYiz19ucvaAgkWcRSmnOitVb
            U932BBVGhLDWtBD8bR/L0lwBO2qUAEBLQ2RrlGoti69VyhprI+FYlP1CbCwVZo5l
            1riYW5sxdLSjVT+oDDIQG2bFmPr8Ih4vmS8EO8dqmDA93sv4u5aNX23DMAOZN96y
            WIIlysTZkk6Zptpzjg==
            =v7MO
            -----END PGP MESSAGE-----
          fp: F86963BF3C1BEF73A3EF3FA75FD8BC12CD3EAD85
    encrypted_suffix: Templates
    version: 3.7.3
