apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: asf
    namespace: asf
spec:
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:VUvN,iv:PHIdVwnOf+LalICU3A2PoJGBETxuRXUa3FMmvCMMuSE=,tag:5dGoAnzvCg2Fq0ut6jN5eg==,type:str]
          labels:
            test-asf-archi-steam-farm: ENC[AES256_GCM,data:yfIPjKg=,iv:7iNqupdtutvRwJkWly1g/RZvmkh+YJo46t5oW6g6WNg=,tag:Yb0Nj3ktJQ7DsiqPwPlzKg==,type:str]
          stringData:
            IPC.config: ENC[AES256_GCM,data:VCi0k7AJRtR+ldPH9PnjVE68swJvmUqB2epTbW/fKt/vRvXsQO9NGLNhApY/D+9U+3oijR/SyPTZ606vFaJ39wrMRcja74qThIEZ3kpIoFEcf/TtbcwtLgTJ3yeL8FDhaKhed/Gv3ddhEyPiXtBpuFy2+J0DxbhCScoNcyg5WxIO8/XyWhZyjVtgEu85/qOqkX3s33IPSokJFY5ViCbx6HwqBuZl+aMKwi5xRqxc0uirXGVrXqO+xgOeAwHYHl6F9AMvPuAiSg4MEUWk6/Iel8hUi3TPgWi6kaEaAw==,iv:JlbWWlJwUcNrnhO6b8op4u4ta4pOeTEZb+9RdphNcMI=,tag:tC91hZb76CriV5SxCaoi4g==,type:str]
            ASF.json: ENC[AES256_GCM,data:JniH8PwkIzT7DeyPPzqn3xL6w0LNXVY2yckm7tgfQ+F9JTmJknL2/aw64bQcNKO0CjVhcHJ7XliRrIH99DADEYDrni4vquFTC4w6s4aaR7+fO9pk7Mpjjokuv9zVCR6OqQ==,iv:ildRMKkjZpyXIsnfq7tDbyz3QwGPvqaa9bBETWdYEls=,tag:RrdSzqSOoFlsFKGmdaeShg==,type:str]
            oni.json: ENC[AES256_GCM,data:t8GOwdk5LJAGzlo8iWypj7MN2yWR0R8rlag2zes0exfoU80No4Q1wMc/rcmNnhJPcytYFURNOlMjX16gBe4L5+JF1Kopc5H0UsoBFmeB45pdH5TjGQu5vi3t6E0OZiYTJn6p40EZnUG+nsxzT/zNddv06Inv9I3dpkWAm9qyDNkfK1qVZ/cXP4FTRYukwqFKXg0z8S12YTBFXeaWlCJ/6S2ohf/1dGed89e+pG3oBCOnbKGbZKAJ1UKp9h9ZT4Xl0KLZj7jqfg2BnvJ6bnfJURX0IiHGt5IOfGf/cvIRpL0q/GRXqn2rTgRS6wHLOEXWIb3f6i5MM+9Bd81VYE75R7FaPOxW1riuCvLodzJGfn0g0hrTij4cdVI3bDcy2nwZvvWPC50xX30bU1+PjfX54rHFszpA7tUhipY=,iv:WtMS7kYlIeRFvxUDpKyd/+hj8YVdLu9hC8Mv0yxX8+s=,tag:XPUHcj4+Ujiz1Jj1JqoMxw==,type:str]
            _tl_.json: ENC[AES256_GCM,data:cUG4psb+/CpdSAIUCQux/d94cmwYigjBKGfOumqG8FPIhVCdorFFVFYGB8qIF8meudsa2xDQAdusIRaKzfM99+OtocEb9CbymnRi3dTMQlGgQDl0nolVMueNU7g5+2O6CEkmDQpb/hQaR7wwzNHDYwL3q/xnO+PCVTjPoshaKbthqnIExVH0AK4wC3aAbm/PKIyl0RdYeRjVeGiWvcT2NoscqVT4fbzp/CWQnzS5T4i1sDgFswCFeOHGDpkKLUJxbR2P0/uYyg6Zw2Y0tpQe6Hkj+AjuFhHJ10eQLRb6JmKpgoJhn/hSdc8UHZUwg9jU+GYxVf/NxIJwBg+Lps5ciqeiA2t39/KVKMNGZFqwMqdiiV12LQgj5f/JjPDi0Y50,iv:rifSmVPfnF9q8rwL/tgJxoWOJuSK82K4hXyNZpEpgbI=,tag:ZEq77qaSR50Pe3yXBURddg==,type:str]
            oni.maFile: ENC[AES256_GCM,data:j08FKAboTmWV4W8COhyfgSPowsELwB+OChMYc/Ted8MlAOg4kNUZuK+1zH6WEuI+vHd7ZYZun5wBjcM+FoUE208w5lAo1o0doRyR6ixHLHVEVoCqAyXVazNJq83NPMFDtNSP23+kaOGArc/WZKEUlBOzxF9U6fyjSOeA0ot3yhS1OwMGvGo891PMB/Cg0P6Cil5GxCtq77NaTlOJNEL/S77fbgI5NgDlGGnz86tFVmJnCOka4gXeFT86bLzeaai71V8UHUmMSGm8AcpnqOgj8cEEHpgK9TYCK19ECwLEZtt/q7KSGvOMBFIJ/zJ6lyrM036liGXlwXilpaiEYhbAXQK+3KDUyv9Q4j9o5pvyManjFHzJzhW/29dU8kRipJShWuk7MsQmh6B7OtMoaF6NLWt1mrFiDFRf1nGrvN1DjfJyE40ipelowNxtXq+BrTbPucBhSuQX1ynlFDtpktkD/uOnH8PWf9YyDEDuVNGDgBV+VjorCI5fMHsVF+4ML+JuQyARz33Mvhc+IeFzziyTjEKEfemFpZpv85dBYfIN4EHOBv4cNHu4VCkm3FiN6Tv5eBr6wHGGIO1+ohwsXx1DMMEVkxFX3k/tf/UaEg2AGJbhBedGp7oPslWdutElvxBecxOHIOc9JgzBFt+E3H2XsA5+E7Ekdj4dCczK4wAKj/8UJd8dyc2R6BYsdZ6vdyZfO56n4Gn/MY2p1Cy/fuzcbj1eca/6gQWK5DHXz+JK30k6Lk+bQcm25XbXhyl2FojMFPqIjH3H+nXxe4xnkDDxHEGBc1yCjaEZpzu3UROS/5b97jHf5YyDHK92vR+8VwzgGPczZhCOu3UaF/K2OUEB1qtenGGnOAT/43W+4AYgLzQDNWW+XV48h5JhETnqXsEwz4dDmSHHHDIpCGFmp3vps2a4tPjjD8MMZHdXu5cLzPPHTkMiitAvWofkDXPTFqzIS4wm9LuG+BaA+qv9li7SwpSc2e3/RKBBpE6WKSWBgb/dLu2oJ+Lp/eWuTkIKpxtXzazX28FlHyZnjLEpDU8udy3F2d/aHD5krX7zrbUu2SFzGrcbNBeIgfwZsk4m0DKVDix4Bdg1uqzY,iv:CVG+aD/5ORg8cwbF9oJvVnFurs/gjsw3VHyj7k0UH+A=,tag:2ub4rCrXwKRqu01p9OFYwg==,type:str]
            _tl_.maFile: ENC[AES256_GCM,data:3lW7ibjJbWueoUjLnxpT3gCSFucBozWkz0iyWk5omTT7DJrQyAsOafnQvcRt5K8jatoNlKGZSP1G/ndLW+lTTyRTD2W6dR53S0jXVMqwWK7q7g9FTtIIxaucLw+esXMRTQPRZQtPtqpsldcQVoyaQXJfDTKzAkXxPbDbFzQ56HB9Qu9IJSNl0rvD1dtSy4D8F5Qjg4/HMx7FLGmi0veloWaK/8SimDxPyEGzA/7V47MNxo2pbtWBvlacHSaXMACLq7csvlwewQzcqWait5MX40xluJBjsUiHalZdtkIscE54RToOVLWfVj4ylPHLyQPUsA3yMHADxjFf29gXxniEU08AGo7T0lbILcHSkz8cvQYCHsiYYX/WM5uBtFh6tobnzwYbe0oRplsXra4DzxaWzeLHxY9pkBhi9M6UpvioM69YOwmvt5ueSbrjPzWoCsW4EbLpiAfnbVjVGKJM0GjH2Ycbigjuw4mFTLyvdzBqnoPO+CuCHXQQ+76orwy/cVYUfzBeg+hxW5sece4S3KgPx7ZTtGE7uChOelqGB3qPJN8mJm3BnRsZIgKRqbf6Iezzl3PwhKFfB3Z64gMxd5xe4k0KT1Yjd8PFKj5a+K+HaPvA9eRwIRX216TZSyCtCAACP2WLZ0QgtGOR1Fl76eKUSkL/tDPP46QedIRr5AGp0XOwhNQ1ynjSaZDT6x3V4kV8cZFVtX5oLV3dm9tqwBMxCVSB2QSF15mNbjF3QdKFqXJwWmMNOigntmL87iMIDKoJoHd3btQ9ZeefFL7Yab3YWmcrS8VGQEJiGYknkdUB0H0TKTg5FcQ4zr645+WbTyFbdat7bYaNOVqT052F2RMAWJ/aPo2m2Od2ECM0bPvc5J6KV4qzmV7exxb3k85uYv910G7MaxBe7ifxp/61JYm778oD3s7wzl9ENI/r+IyevcYDImdSFy0UYsFmjxUe9r/APlugWf7vJhMkIe/J6JGgzJ16yYWIMVvftpRSygFKhbMG57VhibW6L5aCHKkJ4iCYDaPyrDbOLJVL0qrAdLcPf/vY10vX+v0Sl5HpaMCqVAMM6fucaxMVq2Nhm1jFWvxBAgUjny0=,iv:b2Hu87eJsQYcydedQLkCI+kQUM4104Wo6QMQXKsD4to=,tag:9ePOFeeHI3tfix/Y5oJrIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-04T15:01:14Z"
    mac: ENC[AES256_GCM,data:4A8UGRQeoVxMZOpZOrinu9H7unjf0DjnfJ4LNVh7vuGV8T9Vn/rC8PjL2/73rqooF0nLdpuw1DUL+sVjt56eenNjBbXhTvwFB7qr3rhnvJuLlYxrro7t3m8XU3ItsmzUZCsOb30pKqufCHOUty9jIVQ+kfJJrP0tAT8z1EksU0A=,iv:lMmrrsyue3FOdeBSqDxYcW8ocBTW8FbyfkHTBfwCg5M=,tag:u1YBhDlAfpPMfq+GJGKC0A==,type:str]
    pgp:
        - created_at: "2022-11-04T15:01:14Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzeYGILgZyj2AQ//RIFF2r4sXCyFfvtWmuLCCLIYAqF/5tXNxc4VdoV22B87
            EUl4pMPRDybTRfFCPBbS7ueK5Lm7iUxkZo8qKkrVPBEO2TXhd3qXFJqex22O5YQc
            jGaINDgh3tBJZo7dGdyWCPrN/LQKfEgRtf5wYwEnvE7SJHBibaDjA03Vx8cIqFOW
            zL9lb5uJzhyfKn1gTI0RkUxauCle+jb4qEXtwGkFZs98FfohWTl1i0pdXl7WtBwL
            adLWDKViuwthDQAI+7cfp15QuHwn2FU++sAz8VJuT/mlO3ZFMz66jFu6WKFevq0G
            RMK51btQQArhkebtzw/a8lc0hDAFEeXOm9mCDfrS+f/79g7slZ5DO5l+FfU6omqx
            TGg/WlZYifgKCPyFLzo0K4cfn7UbVrKEQ9becpeezdg6JKWOgWH6yPRjpxpKqaL5
            LO6cnP+PF8DQr/uAz3aWQwHegeQk6gzTf0CCfJ/Mq6BOzCquzg8zqLiS0wgYtA6w
            sPkXG42ydztIBWq0m5Hi6zL1QN+y0EUJZyXi8qcmKYZB0Y/mvyYscrcsv0Y62Fbj
            qjtO95NOXvZ8FJS7l2Q0BKD3UxpyRHD3opkm5m0PR0Lb5Bmzqb4DsGUtM0Ax0Yob
            Fq8DL/zG8IxZK64KXhf1Or2+shlHqtXVdLON8/3chr5JsMTTrFx4tfQrGT1ZI13U
            aAEJAhB/4PIUF+2KPTwe48qUgix4inbORIjzjAJ2YYVtsyf7w6qaVEH62tsIfvUO
            UoyFhQSOda+oMNWv0ERmPFF69bPL88N8F8j0lXXV/mLCXDn3n1T8Ej647WVeh9JE
            OxxTYv19y0L2
            =s5S4
            -----END PGP MESSAGE-----
          fp: A35AABA719FAC1A001E375F8EEF7F5B1C5AB1F74
        - created_at: "2022-11-04T15:01:14Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA2EVWQAqdcBfAQv+MMnp0gSGifSx7a9Psu3lZ2hbS3H+/VhXRj5oXZaIw0f/
            7KrjcwimuhOncXkc00RfAHOY4RO0mTzLfzuSZcrIep9CoGXUXRPVetvZdx0MU37R
            Hw5rn2/TUAtCwBjGHej/RLS/bHQxJJDXWzRdtIe/jXNxzXmUnXCk9U5q5fclLsOZ
            ySNzgS+9+GnRPuBXvjwEOOscJ4DClkPXOK/Ls0uQbZEQY9hyv4NH0DWL2zT64MTK
            NF7K2Jv8qljLWDTJa0dNG0bJ1gOxGaHugicEPkuM9yJeeHzTMDoPm98OMAY9Ie3g
            //gXVyj5rBbn0YpVyKKjCzAlzT6BD8nJGz8lCp4jNctnbwvMxiYvkMTk6mIfR31h
            wZscq3nLW3z0vA00OmO7CR0tFDOZ5F5Y47XT284H4KYGv4zJsbesAPfXccj/LLdF
            CMkPhYU1jjqZ3X/hVfCTxXC9w6SEAAeUQiwZB1WqJ2U4B/+jPE3EsFFddX0GcWea
            GwqOQYeRDo58EUelGsXa0l4BM13yiPYfnIADNz7lChhYp2HXjvSaXe9cz+1hXjqo
            mRu4czpFYAwbVILtOLYRJeaxMGrdh/Pwpjg0+TQGWaRGVTqb/5k1mg0vbbT65tf/
            2pnpjThG6qpO7roUDmwP
            =S8Hz
            -----END PGP MESSAGE-----
          fp: F86963BF3C1BEF73A3EF3FA75FD8BC12CD3EAD85
    encrypted_suffix: Templates
    version: 3.7.3
