apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: shared
    namespace: kube-system
spec:
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:qlz1rgYgHduJp1l7N1asb23xaw30,iv:jtFu4gUVSJqC3hUQdN+ulaCKXrV0580pPen/SLF1EAA=,tag:whQRUcazyHQBxxquZbN7NQ==,type:str]
          annotations:
            kubed.appscode.com/sync: ""
          type: ENC[AES256_GCM,data:6oKdPZLPzWFOsj5Wy8mEIjz1lCiHN0yugc5PPV2E,iv:Oe1drcf2KOGBI0HQGZMjeJJvvDkbVdb5qnyTjj5e/Mo=,tag:9+tYdUVcuCN3fc4wcnbxjA==,type:str]
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:j5Amk5vuNPAg0FZCNWaUxkLwGSmIb13uIgnxbiLa9oJ5azPCJ64FI6CCOH2etgVkO2D5254Dq44AujBMR3jKxxY37/9mFcm9qwqoVN+WtVmVr8im6RnAI0pAhr9Oa5q63SnMkD7Yd0xj03j0qAz2wr6GfFKmWmQL/QfTbz4oV6753o5DMLP/cVKoxkrGNRHXX7OHWF+lL8UItd/6L3jqs1Guv1yQwUrnymU63ww7LVln0CN2sh+IZaxreGmi1WbhdEG+EtI=,iv:OJcLdFIFN4TzDq4f7Q+f0UFrXX6sFgiMw/X2oipRg2s=,tag:/QqPVPgTYIKRWO3j90UZIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-25T14:11:17Z"
    mac: ENC[AES256_GCM,data:Rj3ZpDi1EUdHX1E9odhpYQLaJ4Lb753qsLxXLkOiPsAQ61/SC2Ms4XfzaXRG/haG3b+aYoujj6gP3v2pJWeGQwFRLfPZBjusIm1krp61YJAEK6yO0I91uWPMHPV7sfWDh6JjgUjj0rFgwPntTc28IigBcB7ZciT1QDY8jkNQrl4=,iv:k2tcohyXNBCXdABz6gaIZaM7Tml1eXvmSx6RsTMbZME=,tag:ZvFaX9fs3Yn89ybEelDMVg==,type:str]
    pgp:
        - created_at: "2022-11-25T14:10:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzeYGILgZyj2AQ//S/oe8pQ2oTOqBWnvmxqxGKEXheztdhwff8KqYT4rmZ5P
            d702VdW/nwpF1ndgVoj+upDhhKo2auv/Up9OLhLkA6X3C6sbSsd8oul5mrtAcgxI
            SQR2en9J0Dc+cUoLykh+iEI88/u9pssKlkdOU8GQWet4lmOpL8mZ1MUHXGHVhRVk
            rH67szWFQP4fX1MsUILDvl3HbqWG4gId8UKZ9TQ2+u4tVTlQV8Wj9pi2zH7iqFo3
            vlQW7d/l2rgvoq4PJMibM7PZ+FvVdFwpu8ykldJt6RxBXu18IG3uw9mVPTMGBXDy
            GXxQwg8EilJwIae4LxXbos+EyDsqQm0wBfaR+M2Wx3w8aqZ6mLHsb53MOY4EJKYh
            RZxEbaVly0kQNn1OSZuBuGtd6xcDq9cTMrOp8BsVbXLXUznkDZ6+0P4U3PRjQA8t
            pf4c4scZSuraQXFx6AwWXg3UYFLDDnhuw7lLFtz2mTWs86Z/ARq9hh15wHQJV7eh
            BOX2mfHhAJD4Id+IgEUeDSHRR/AtrxE8741GBysJ2XGwnxkx6aFEYgkR0Oq8SEGk
            pdvutCFzEFsu1teJNfIg3CRhgVWfsmhn3JtaNpWGHOetmbZ5kQLGmUacbUL4+SBE
            3CLpqld2OQEVE+NMyRtaLSWZ3uWuVldO4zV89vtondeZ+vo8OyOskdjXi9klscXU
            aAEJAhB4fggy1SRrjh2BadWhKHXl3MYiA/yILjN6UGzQBBM+DxD7IzAqIRZ05wqm
            h3Y4140djS6VFXNOGttZrJ1sUHep1rpOaJ3wzhdwxRNAi3t/1W+kN5fcEgMpJLQP
            eGVeWun1LXtH
            =JzLQ
            -----END PGP MESSAGE-----
          fp: A35AABA719FAC1A001E375F8EEF7F5B1C5AB1F74
        - created_at: "2022-11-25T14:10:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA2EVWQAqdcBfAQv+NyYOa/xSDDRyEx7+cwqOxh0lfxsEr1UxFPQ1OQgmW3g0
            PMb7sEyLiUpNejFiIX7a08MOXgLGYHieWojnZsoiQv6bx9txglOq2Qa59uu2VKE4
            rEpIDslqZCsilj8biXOusiInvBEGn8F1ys2YUYg/keeRlDGsB7iAbHyINBHmh384
            IfW0zpglaoRABQEq65RhzU97jthx5sag1si7vFxNpWKydQx5nyg5B/AGgCuKhVWj
            /o8XdrcjXy3o328lF33+7kh+BqX8b0IhhUvhl7pXbCYjqYWET9F7SERJdCLS7xsu
            Rp9cM6JElU1JHE+j3bi1kS72GZrEcgNfSecCcp1EhNn3nYaZgzA0ci+x4t94VeGI
            0eDePfyKqVw+GjzR7UqjsHwt1f3qWjMZMk+4ZBUjAL9VFbEk8u1VjKyp7Q5HZh83
            +uYT2vCXkkU6caKKSPjf+QZ1BwfCvsU91KuZB6LuzyAqDHEiik9YGzss5p7Ozhfk
            4cCgZYEBy5WrOGTMTXqP0l4BcNToG7XuCb390tFAiurmwBHqD1DEkO3VfGg1Z0db
            aUfLy8vJM8KAJZ/EmFlRd/EMgtlgszYjAM2sDLWYWaxmadcn4Xj7LdUcYgkDKOLR
            mYb5PxZunVDKAob6SXAS
            =DxFV
            -----END PGP MESSAGE-----
          fp: F86963BF3C1BEF73A3EF3FA75FD8BC12CD3EAD85
    encrypted_suffix: Templates
    version: 3.7.3
