apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pandora.fullname" . }}-bot
  labels:
    {{- include "pandora.labels" . | nindent 4 }}
    role: bot
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pandora.selectorLabels" . | nindent 6 }}
      role: bot
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pandora.selectorLabels" . | nindent 8 }}
        role: bot
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pandora.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        {{- range $key, $val := .Values.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
        {{- end }}
        envFrom:
        {{- range .Values.envSecrets }}
        - secretRef:
            name: {{ . }}
        {{- end }}
        volumeMounts:
        - name: config-overrides
          mountPath: /opt/pandora-overrides/
      volumes:
      - name: config-overrides
        projected:
          sources:
          - configMap:
              name: pandora-configs
          {{- range .Values.config.secrets }}
          - secret:
              name: {{ . }}
          {{- end }}
          {{- range .Values.config.configmaps }}
          - configMap:
              name: {{ . }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
